spring:
  datasource:
    url: jdbc:h2:./acdb
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath*:schema.sql
  h2:
    console:
      enabled: true

logging:
  level:
    root: DEBUG
  pattern.charset: UTF-8


quickfix.session.settings.path: session.settings